### ISSUE TITLE
source .bashrc in setup.bash not working

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/speech_recognition#2]
```.bashrc``` is not sourcing and as a result the file ```LASeR_env.bash``` does not source.

This leads to environment variables (**required** for the setup and use of toolkit) being unset.

**Comment by MatthijsBurgh** [comment]
Setup files are in our tue-env repo. This is actually a little bit ugly. Although not everything in those setup files should be in the packages as well. So a combination would be better.

**Comment by MatthijsBurgh** [comment]
I checked your setup.bash. There is a `source ~/.bashrc` in there. Which shouldn't be the case, because it would create a circular sourcing. Plus the defined functions are named very general. I don't prefer it, to have these functions available in my bash environment.

**Comment by ar13pit** [comment]
> Setup files are in our tue-env repo. This is actually a little bit ugly. Although not everything in those setup files should be in the packages as well. So a combination would be better.

I didn't quite understand what you are trying to say here. The setup file I am writing is basically installing all the dependencies and libraries for the speech recognition toolkit to work. There is no relation to ROS packages at the moment all it needs to be created and isn't readily available.

As ```setup.bash``` is not being sourced, rather being executed, the functions shouldn't be there in the bash environment. I think I should change the name of the file to install.bash as it can easily be confused with file generated by catkin.

As the file is being executed instead of being sourced (check the Dockerfile), will there still be an issue of circular sourcing?

**Comment by MatthijsBurgh** [comment]
Just to be clear, you are not using the installer, `tue-get`, (in `tue-env` repo) to install your package at the moment, so anything in there doesn't apply to your situation yet.

If a target is installed by `tue-get`, first `install.bash` is executed, then `install.yaml` is parsed. Also is checked if the target has a `setup` file, which should be a bash file. This file will be added to a list, which will be sourced by `~/.tue/setup.bash`, which is sourced in `~/.bashrc`.

(An improvement would be if it also checks if a `setup(.bash)` file exists in the package itself and it to the same list. This is not the case yet)

**Comment by ar13pit** [comment]
I'll have a talk with you about setting up the package to be installed with tue-get as I need to understand that. 

Meanwhile, I have solved this issue of ```source ~/.bashrc``` not working inside the script. The fix is simple. For the sourcing to happen, ```~/.bashrc``` must be executed in an interactive environment which can be done by ```set -i```. After the sourcing happens, I revert back to non-interactive environment by ```set +i```.

I am closing this issue.
