### ISSUE TITLE
Targets do not exist while installing repo

### ISSUE THREAD

**Issue by dvdinth** [tue-robotics/speech_recognition#7]
When running `tue-get install speech-recognition-dev`, the installations gives 2 errors:

`Error while installing target 'ros-audio_capture': Target 'gstreamer1.0' does not exist.`

And:

`Error while installing target 'ros-speech_recognition': Target 'roslint' does not exist.`

**Comment by ar13pit** [comment]
I know we get this error message but these packages do get installed. So this is more an error with tue-env than this repo. But as we upgrade tue-env later in March, this will be solved.

**Comment by ar13pit** [comment]
Targets have been updated.
