### ISSUE TITLE
Notes on installing and building

### ISSUE THREAD

**Issue by dvdinth** [tue-robotics/speech_recognition#8]
So below are some notes on things I encountered while trying to get a correct installation of kaldi, gstreamer, and the appropriate plugins. It's mostly in chronological order in which I ran commands

**A few interesting websites:**
https://github.com/alumae/kaldi-gstreamer-server
https://nixingaround.blogspot.com/2016/07/installing-kaldi-and-kaldi-gstreamer.html
http://kaldi-asr.org/doc/online_programs.html
https://github.com/kaldi-asr/kaldi/tree/master/src/gst-plugin

**tue-get install speech-recognition-dev:**
Suggests to install sudo apt-get install automake autoconf
And then also sudo apt-get install libatlas3-base
Problem installing sequitur

**tue-make**
(wait for a long time until kaldi is done making)

**Stuff that I was required to install to get everything to work (such as the digits example):**
p7zip-full
SRILM (move from repo speech_recognition/tools to ~/src/kaldi_speech/tools/ and then run the install_srilm.sh)
gawk
ros-kinetic-roslint

I also performed the steps in INSTALL in ~/src/kaldi_speech/ but I think that was unnecessary.

**gst-plugin install stuff:**
kaldi_speech/tools install_portaudio.sh
Go to ~/src/kaldi_speech/src/online and make the library (type in make in the terminal at this location)
After that, run 'make depend' and then 'make' in the gst-plugin folder (kaldi_speech/src/gst_plugin).
run 'export GST_PLUGIN_PATH=$KALDI_ROOT/src/gst-plugin' and then 'gst-inspect-1.0 onlinegmmdecodefaster' to test if it created the plugin correctly

export GST_PLUGIN_PATH=$KALDI_ROOT/src/gst-plugin
then run run-live.py in ~/src/kaldi_speech/egs/voxforge/gst_demo (might first need to execute run-simulated.sh)

**ALTERNATIVE ONLINE_DEMO**

go to ~/src/kaldi_speech/src and run 'make ext'
go to ~/src/kaldi_speech/egs/voxforge/online_demo
read the README

while in ~/src/kaldi_speech/egs/voxforge/online_demo, run this in a terminal:
./../../../src/onlinebin/online-gmm-decode-faster --rt-min=0.5 --rt-max=0.7 --max-active=4000 --beam=12.0 --acoustic-scale=0.0769 online-data/models/tri2b_mmi/model online-data/models/tri2b_mmi/HCLG.fst online-data/models/tri2b_mmi/words.txt 1:2:3:4:5 online-data/models/tri2b_mmi/matrix

**Comment by ar13pit** [comment]
Great. I'll make appropriate changes and test cases for the setup.

**Comment by ar13pit** [comment]
The new install script takes everything into account
